sudo: required

language: python
python:
  - "3.6"
cache: pip

services:
  - docker

before_install:
- docker-compose -f infrastructure/mongo_db/test_setup.yml up -d

install:
  - pip install -r requirements/dev.txt

script:
- pytest iclr_wrap_up/ -v